
#------L--O--C--A--L------H--O--S--T-------#

# Login first
http://localhost:3000/auth/me

#-------------TASKS-----------------#
# GET all
GET http://localhost:3000/tasks
###

# GET task by ID
GET http://localhost:3000/tasks/69d6f812760bfb88c95aa413
###

# POST task (create new task)
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "Prepare Dinner",
  "description": "Mom is comming today",
  "status": "pending",
  "priority": "high",
  "dueDate": "2026-04-15"
}
###

# PUT (update task)
PUT http://localhost:3000/tasks/69d6f8f3760bfb88c95aa414
Content-Type: application/json

{
  "title": "Prepare Breakfast",
  "description": "Mom is comming today",
  "status": "pending",
  "priority": "low",
  "dueDate": "2026-04-14"
}
###

# DELETE (delete task by id)
DELETE http://localhost:3000/tasks/69d6f8f3760bfb88c95aa414


##### -------------- R--E--N--D--E--R -----------------####

#------LOGIN FIRST VIA BROWSER----------#
https://cse341-node-8.onrender.com/auth/google
###

#-------------TASKS-----------------#
# GET all
GET https://cse341-node-8.onrender.com/tasks
###

# GET task by ID
GET https://cse341-node-8.onrender.com/tasks/69d6f812760bfb88c95aa413
###

# POST task (create new task)
POST https://cse341-node-8.onrender.com/tasks
Content-Type: application/json

{
  "title": "Prepare Dinner",
  "description": "Mom is comming today",
  "status": "pending",
  "priority": "high",
  "dueDate": "2026-04-15"
}
###

# PUT (update task)
PUT https://cse341-node-8.onrender.com/tasks/69d3263c258b196fdb97d42e
Content-Type: application/json

{
  "title": "Prepare Breakfast",
  "description": "Mom is comming today",
  "status": "pending",
  "priority": "low",
  "dueDate": "2026-04-14"
}
###

# DELETE (delete task by id)
DELETE https://cse341-node-8.onrender.com/tasks/69d3263c258b196fdb97d42e
###







