
#------L--O--C--A--L------H--O--S--T-------#

#-------------TASKS-----------------# cse341-node-8.onrender.com
# GET all
GET http://localhost:3000/tasks
###

# GET task by ID
GET http://localhost:3000/tasks/69d5a271c673eb25330c571d
###

# POST task (create new task)
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "Prepare Dinner",
  "description": "Mom is comming today",
  "status": "pending",
  "priority": "high",
  "dueDate": "2026-04-15"
}
###

# PUT (update task)
PUT http://localhost:3000/tasks/69d5a271c673eb25330c571d
Content-Type: application/json

{
  "title": "Prepare Breakfast",
  "description": "Mom is comming today",
  "status": "pending",
  "priority": "low",
  "dueDate": "2026-04-14"
}
###

# DELETE (delete task by id)
DELETE http://localhost:3000/tasks/69d5a271c673eb25330c571d
###

#------------USERS-------------#

# GET check
GET http://localhost:3000/users/69d3263c258b196fdb97d42e
###

##### -------------- R--E--N--D--E--R -----------------####

#-------------TASKS-----------------#
# GET all
GET https://cse341-node-6.onrender.com/tasks
###

# GET task by ID
GET https://cse341-node-6.onrender.com/tasks/69d3263c258b196fdb97d42e
###

# POST task (create new task)
POST https://cse341-node-6.onrender.com/tasks
Content-Type: application/json

{
  "title": "Prepare Dinner",
  "description": "Mom is comming today",
  "status": "pending",
  "priority": "high",
  "dueDate": "2026-04-15"
}
###

# PUT (update task)
PUT https://cse341-node-6.onrender.com/tasks/69d3263c258b196fdb97d42e
Content-Type: application/json

{
  "title": "Prepare Breakfast",
  "description": "Mom is comming today",
  "status": "pending",
  "priority": "low",
  "dueDate": "2026-04-14"
}
###

# DELETE (delete task by id)
DELETE https://cse341-node-6.onrender.com/tasks/69d3263c258b196fdb97d42e
###

#------------USERS-------------#
# GET all
GET https://cse341-node-6.onrender.com/users
###

# GET user by ID
GET https://cse341-node-6.onrender.com/users/69d3263c258b196fdb97d42e
###

# POST user (create new user)
POST https://cse341-node-6.onrender.com/users
Content-Type: application/json

{
  "username": "Alberto5",
  "password": "A1bert025@"
}
###

# UPDATE user
PUT https://cse341-node-6.onrender.com/users/69d3263c258b196fdb97d42e
Content-Type: application/json

{
  "username": "Alberto2500",
  "password": "A1bert025@12"
}
###

# DELETE user
DELETE https://cse341-node-6.onrender.com/users/69d3263c258b196fdb97d42e






