
#------L--O--C--A--L------H--O--S--T-------#

#-------------TASKS-----------------#
# GET all
GET http://localhost:3000/tasks
###

# GET task by ID
# GET http://localhost:3000/tasks/69d149546dde7fb059e06bbc
###

# POST task (create new task)
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "Prepare Dinner",
  "description": "Mom is comming today",
  "status": "pending",
  "priority": "high",
  "dueDate": "2026-04-15",
  "userId": "800"
}
###

# PUT (update task)
# PUT http://localhost:3000/tasks/69d1d771f43478fd060ac54f
Content-Type: application/json

{
  "title": "Prepare Breakfast",
  "description": "Mom is comming today",
  "status": "pending",
  "priority": "very high",
  "dueDate": "2026-04-14",
  "userId": "811"
}
###

# DELETE (delete task by id)
# DELETE http://localhost:3000/tasks/69d1d771f43478fd060ac54f
###

#------------USERS-------------#
# GET all
GET http://localhost:3000/users
###

# POST user (create new user)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Alberto Martinez",
  "email": "albert_m@gmail.com",
  "role": "student",
  "phone": "503-1234-5678",
  "address": "DF, Mexico",
  "department": "Computer Science",
  "status": "active"
}

##### -------------- R--E--N--D--E--R -----------------####

#-------------TASKS-----------------#
# GET all
GET https://cse341-node-5.onrender.com/tasks
###

# GET task by ID
# GET https://cse341-node-5.onrender.com/tasks/69d1fb45eeffd84eddea0af1
###

# POST task (create new task)
POST https://cse341-node-5.onrender.com/tasks
Content-Type: application/json

{
  "title": "Finish homework week 5",
  "description": "Complete lesson 5 assignment",
  "status": "in progress",
  "priority": "high",
  "dueDate": "2026-04-11"
}
###

# PUT (update task)
# PUT https://cse341-node-5.onrender.com/tasks/69d1ffb96519d8ab4331c78c
Content-Type: application/json

{
  "title": "lesson 5",
  "description": "Complete lesson 5",
  "status": "progress",
  "priority": "high",
  "dueDate": "2026-04-30"
}
###

# DELETE (delete task by id)
#DELETE https://cse341-node-5.onrender.com/tasks/69d1ffb96519d8ab4331c78c
###

#----------USERS-----------#
# GET all
GET https://cse341-node-5.onrender.com/users
###

# POST user (create new user)
POST https://cse341-node-5.onrender.com/users
Content-Type: application/json

{
  "name": "Mery Jackson",
  "email": "j_mery@example.com",
  "role": "artist"
}





