
# ---------- LOCAL -----------#
# Test POST to create a new contact /201
POST http://localhost:3000/contacts
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Wilson",
    "email": "jwilsonj@gmail.com",
    "favoriteColor": "Gray",
    "birthday": "1999-03-15"
}

###
# Test PUT to update a contact /204
PUT http://localhost:3000/contacts/698c0434fdde03972bc01d39
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Walker",
    "email": "jwilsonj@gmail.com",
    "favoriteColor": "Black",
    "birthday": "1999-03-15"
}
###
# Test DELETE to delete a contact /200
DELETE http://localhost:3000/contacts/698c0434fdde03972bc01d39
###

# ----------- RENDER ----------#

# Test POST to create a new contact /201
POST https://cse341-node-4.onrender.com/contacts
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Wilson",
    "email": "jwilsonj@gmail.com",
    "favoriteColor": "Gray",
    "birthday": "1999-03-15"
}

###
# Test PUT to update a contact /204
PUT https://cse341-node-4.onrender.com/contacts/698c0434fdde03972bc01d38
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Walker",
    "email": "jwilsonj@gmail.com",
    "favoriteColor": "Black",
    "birthday": "1999-03-15"
}
###
# Test DELETE to delete a contact /200
DELETE https://cse341-node-4.onrender.com/contacts/698c0434fdde03972bc01d38
