
# get all contacts (LOCAL)
GET http://localhost:3000/contacts
###

# get single contact
GET http://localhost:3000/contacts/698c0434fdde03972bc01d37
###
# Render (all contacts)
GET https://cse341-node-ytfz.onrender.com/contacts
###

# Single contacts
GET https://cse341-node-ytfz.onrender.com/contacts/698c0434fdde03972bc01d37
###

# Test POST to create a new contact /201
POST http://localhost:3000/contacts
Content-Type: application/json

{
    "firstName": "Edgardo",
    "lastName": "Jhonson",
    "email": "camij.nj@gmail.com",
    "favoriteColor": "White",
    "birthday": "1989-03-15"
}

###
# Test PUT to update a contact /204
PUT http://localhost:3000/contacts/69c5a50de54fe985d56b06a7
Content-Type: application/json

{
    "firstName": "Rami",
    "lastName": "Salas",
    "email": "rami56@outlook.com",
    "favoriteColor": "Orange",
    "birthday": "1999-04-19"
}
###
# Test DELETE to delete a contact /200
DELETE http://localhost:3000/contacts/69c5a2c7e54fe985d56b06a6