
# get all contacts
GET http://localhost:3000/contacts

# get single contact
GET http://localhost:3000/contacts/698c0434fdde03972bc01d37
GET http://localhost:3000/contacts/698c0434fdde03972bc01d38
GET http://localhost:3000/contacts/698c0434fdde03972bc01d39

# Render (all contacts)
GET https://cse341-node-ytfz.onrender.com/contacts
# Single contacts
GET https://cse341-node-ytfz.onrender.com/contacts/698c0434fdde03972bc01d37
GET https://cse341-node-ytfz.onrender.com/contacts/698c0434fdde03972bc01d38
GET https://cse341-node-ytfz.onrender.com/contacts/698c0434fdde03972bc01d39
